### ISSUE TITLE
Traceback Error for the "read_png" module

### ISSUE THREAD

**Issue by Rice14** [vvanirudh/Pixel-Art#2]
Hi there,

May be a simple issue on my part, but I'm getting this error:
```
Traceback (most recent call last):
  File "C:\Users\Owner\Downloads\Pixel-Art-master\Pixel-Art-master\main.py", line 1, in <module>
    from input import read_png
  File "C:\Users\Owner\Downloads\Pixel-Art-master\Pixel-Art-master\input.py", line 1, in <module>
    import png # Using pypng module
ImportError: No module named 'png'
```
My first instinct was that this may be a version error.  I tried running this on both Python 3.4 and 3.6.  I notice that "raw_input" was used throughout the code, which is usually indicative of a legacy version of Python.  Which version of Python was this code written in?

**Comment by vvanirudh** [comment]
Looks like you need to install `pypng` package (https://pypi.python.org/pypi/pypng)

The code was written in Python 2.7

**Comment by Rice14** [comment]
Thanks for the info. Might be worth putting Python version info and module requirements in Readme.md

**Comment by vvanirudh** [comment]
Thank you! Will do
